'use strict';
const $ = s => document.querySelector(s);
const escapeHTML = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules = window.featureModules;
const config = {
 '01':{label:'Tổng quan điều hành',icon:'◫',type:'dashboard',tabs:['Tổng quan','Phạm vi tính năng'],action:'Tạo công việc'},
 '02':{label:'Khách hàng',icon:'♧',type:'table',tabs:['Danh sách khách hàng','Phạm vi tính năng'],action:'Thêm khách hàng',entity:'khách hàng',cols:['Khách hàng','Người liên hệ','Phụ trách','Trạng thái'],fields:['Tên khách hàng','Người liên hệ / Điện thoại','Nhân viên phụ trách'],rows:[['KH-001','Ban quản lý The Sun Avenue','Trần Minh · 0901 234 567','Nguyễn Hà','Đang hoạt động'],['KH-002','Công ty An Phú Land','Lê Anh · 0902 345 678','Nguyễn Hà','Đang hoạt động'],['KH-003','Khách sạn Riverside','Phạm Vy · 0903 456 789','Trần Linh','Tiềm năng'],['KH-004','Chung cư Green Valley','Ngô An · 0904 567 890','Trần Linh','Đang hoạt động'],['KH-005','Tòa nhà Minh Long','Vũ Nam · 0905 678 901','Nguyễn Hà','Cần chăm sóc']]},
 '03':{label:'Kinh doanh & báo giá',icon:'↗',type:'board',tabs:['Pipeline','Báo giá & khảo sát','Phạm vi tính năng'],action:'Thêm cơ hội',entity:'cơ hội',cols:['Cơ hội / Báo giá','Giá trị dự kiến','Phụ trách','Trạng thái'],fields:['Tên cơ hội / Công trình','Giá trị dự kiến','Nhân viên kinh doanh'],states:['Tiếp nhận','Khảo sát','Báo giá','Đàm phán'],rows:[['CH-001','Bảo trì tòa nhà An Phú','120.000.000 ₫','Nguyễn Hà','Tiếp nhận'],['CH-002','Lắp đặt thang nhà phố Q.7','480.000.000 ₫','Trần Linh','Khảo sát'],['CH-003','Thay bộ điều khiển Riverside','85.000.000 ₫','Nguyễn Hà','Báo giá'],['CH-004','Gia hạn Green Valley','240.000.000 ₫','Trần Linh','Đàm phán']]},
 '04':{label:'Công trình & thang máy',icon:'▥',type:'table',tabs:['Hồ sơ thiết bị','Phạm vi tính năng'],action:'Thêm thang máy',entity:'thang máy',cols:['Thang máy / Công trình','Thông số kỹ thuật','Bảo trì gần nhất','Trạng thái'],fields:['Tên thang máy / Công trình','Hãng · Model · Tải trọng','Ngày bảo trì gần nhất'],rows:[['TM-001','The Sun Avenue · Thang A1','Mitsubishi · 1.000 kg · 1,5 m/s','05/10/2026','Đang hoạt động'],['TM-002','The Sun Avenue · Thang A2','Mitsubishi · 1.000 kg · 1,5 m/s','06/10/2026','Đang sửa chữa'],['TM-003','Riverside · Thang khách','Schindler · 750 kg · 1 m/s','02/10/2026','Đang hoạt động'],['TM-004','Green Valley · Thang B1','Otis · 1.350 kg · 1,75 m/s','01/10/2026','Chờ kiểm định']]},
 '05':{label:'Hợp đồng',icon:'▤',type:'table',tabs:['Danh sách hợp đồng','Phạm vi tính năng'],action:'Tạo hợp đồng',entity:'hợp đồng',cols:['Hợp đồng / Khách hàng','Giá trị hợp đồng','Ngày hết hạn','Trạng thái'],fields:['Tên hợp đồng / Khách hàng','Giá trị hợp đồng','Ngày hết hạn'],rows:[['HD-001','Bảo trì · The Sun Avenue','240.000.000 ₫','31/12/2026','Có hiệu lực'],['HD-002','Bảo trì · Green Valley','180.000.000 ₫','31/10/2026','Sắp hết hạn'],['HD-003','Lắp đặt · An Phú Land','480.000.000 ₫','15/06/2027','Có hiệu lực'],['HD-004','Sửa chữa · Riverside','85.000.000 ₫','01/10/2026','Hết hạn']]},
 '06':{label:'Lịch bảo trì',icon:'▦',type:'calendar',tabs:['Lịch tháng','Danh sách lịch','Phạm vi tính năng'],action:'Đặt lịch bảo trì',entity:'lịch bảo trì',cols:['Công việc / Thiết bị','Ngày hẹn','Kỹ thuật viên','Trạng thái'],fields:['Công việc / Thiết bị','Ngày hẹn (YYYY-MM-DD)','Kỹ thuật viên'],states:['Đã lên lịch','Chờ duyệt dời lịch','Hoàn thành'],rows:[['BT-001','Bảo trì · The Sun Avenue A1','2026-10-08','Lê Minh Tuấn','Đã lên lịch'],['BT-002','Bảo trì · Riverside','2026-10-12','Trần Quốc Huy','Đã lên lịch'],['BT-003','Bảo trì · Green Valley','2026-10-15','Nguyễn Hoàng','Chờ duyệt dời lịch'],['BT-004','Bảo trì · Minh Long','2026-10-20','Lê Minh Tuấn','Đã lên lịch']]},
 '07':{label:'Sự cố & cứu hộ',icon:'ϟ',type:'table',tabs:['Trung tâm sự cố','Phạm vi tính năng'],action:'Tiếp nhận sự cố',entity:'sự cố',cols:['Sự cố / Thiết bị','Mức độ · SLA còn lại','Kỹ thuật viên','Trạng thái'],fields:['Nội dung sự cố / Thiết bị','Mức độ · SLA','Kỹ thuật viên'],states:['Chờ tiếp nhận','Đang xử lý','Đã khắc phục'],rows:[['SC-001','Thang A2 dừng tầng · Sun Avenue','Khẩn cấp · 18 phút','Trần Quốc Huy','Đang xử lý'],['SC-002','Cửa tầng đóng chậm · Riverside','Trung bình · 2 giờ','Chưa phân công','Chờ tiếp nhận'],['SC-003','Tiếng ồn cabin · Green Valley','Thấp · Đạt SLA','Lê Minh Tuấn','Đã khắc phục']]},
 '08':{label:'Công việc & điều phối',icon:'☷',type:'board',tabs:['Bảng điều phối','Danh sách công việc','Phạm vi tính năng'],action:'Tạo công việc',entity:'công việc',cols:['Công việc / Công trình','Lịch hẹn','Kỹ thuật viên','Trạng thái'],fields:['Tên công việc / Công trình','Lịch hẹn','Kỹ thuật viên'],states:['Chưa phân công','Đã phân công','Đang thực hiện','Hoàn thành'],rows:[['CV-001','Bảo trì · The Sun Avenue','08/10 · 08:30','Lê Minh Tuấn','Đang thực hiện'],['CV-002','Sửa cửa tầng · Riverside','08/10 · 10:00','Trần Quốc Huy','Đã phân công'],['CV-003','Kiểm định · Green Valley','08/10 · 14:00','Chưa phân công','Chưa phân công'],['CV-004','Bảo trì · Minh Long','08/10 · 07:30','Nguyễn Hoàng','Hoàn thành'],['CV-005','Bảo trì · An Phú','08/10 · 15:00','Lê Minh Tuấn','Đã phân công']]},
 '09':{label:'Kỹ thuật viên & hiện trường',icon:'♙',type:'field',tabs:['Ứng dụng hiện trường','Đội ngũ kỹ thuật','Phạm vi tính năng'],action:'Thêm kỹ thuật viên',entity:'kỹ thuật viên',cols:['Kỹ thuật viên','Chuyên môn','Khu vực','Trạng thái'],fields:['Tên kỹ thuật viên','Chuyên môn / Chứng chỉ','Khu vực phụ trách'],rows:[['KT-001','Lê Minh Tuấn','Bảo trì · Mitsubishi','TP. Thủ Đức','Đang làm việc'],['KT-002','Trần Quốc Huy','Cứu hộ · Schindler','Quận 1, Quận 3','Đang làm việc'],['KT-003','Nguyễn Hoàng','Kiểm định · Otis','Quận 7','Sẵn sàng'],['KT-004','Võ Thanh Bình','Điện · Điều khiển','Bình Thạnh','Sẵn sàng']]},
 '10':{label:'Kiểm định & bảo hành',icon:'◇',type:'table',tabs:['Hồ sơ an toàn','Phạm vi tính năng'],action:'Thêm hồ sơ kiểm định',entity:'hồ sơ kiểm định',cols:['Hồ sơ / Thiết bị','Ngày kiểm định','Hiệu lực đến','Trạng thái'],fields:['Thiết bị / Hồ sơ kiểm định','Ngày kiểm định','Hiệu lực đến'],rows:[['KD-001','The Sun Avenue · Thang A1','15/11/2025','15/11/2026','Sắp hết hạn'],['KD-002','Green Valley · Thang B1','01/10/2025','01/10/2026','Hết hạn'],['KD-003','Riverside · Thang khách','12/06/2026','12/06/2027','Có hiệu lực']]},
 '11':{label:'Kho vật tư & phụ tùng',icon:'▧',type:'table',tabs:['Tồn kho','Phạm vi tính năng'],action:'Thêm vật tư',entity:'vật tư',cols:['Vật tư / Phụ tùng','Tồn kho · Đơn vị','Vị trí kho','Trạng thái'],fields:['Tên vật tư / Phụ tùng','Số lượng · Đơn vị','Vị trí kho'],rows:[['VT-001','Cảm biến cửa tầng','24 · Bộ','Kho chính · A-01','Đủ tồn kho'],['VT-002','Cáp tải Ø10 mm','120 · Mét','Kho chính · B-02','Đủ tồn kho'],['VT-003','Bo mạch điều khiển','2 · Bộ','Kho chính · A-03','Dưới tồn tối thiểu'],['VT-004','Dầu bôi trơn ray','18 · Lít','Kho Q.7 · C-01','Đủ tồn kho']]},
 '12':{label:'Doanh thu & công nợ',icon:'₫',type:'table',tabs:['Thanh toán & công nợ','Phạm vi tính năng'],action:'Ghi nhận thanh toán',entity:'khoản thanh toán',cols:['Thanh toán / Khách hàng','Số tiền','Hạn thanh toán','Trạng thái'],fields:['Khách hàng / Nội dung thanh toán','Số tiền','Hạn thanh toán'],states:['Chờ thanh toán','Đã thanh toán','Quá hạn'],rows:[['TT-001','The Sun Avenue · Quý IV','60.000.000 ₫','15/10/2026','Chờ thanh toán'],['TT-002','Green Valley · Quý III','45.000.000 ₫','30/09/2026','Quá hạn'],['TT-003','An Phú · Đợt 1','144.000.000 ₫','05/10/2026','Đã thanh toán'],['TT-004','Riverside · Sửa chữa','25.000.000 ₫','20/10/2026','Chờ thanh toán']]},
 '13':{label:'Chăm sóc & thông báo',icon:'✉',type:'table',tabs:['Lịch sử chăm sóc','Phạm vi tính năng'],action:'Soạn thông báo',entity:'thông báo',cols:['Nội dung / Khách hàng','Kênh liên hệ','Thời gian','Trạng thái'],fields:['Nội dung / Khách hàng','Kênh liên hệ','Thời gian dự kiến'],states:['Bản nháp','Đã gửi (mẫu)','Chờ xử lý'],rows:[['TB-001','Nhắc lịch bảo trì · Sun Avenue','Zalo OA','07/10 · 16:00','Đã gửi (mẫu)'],['TB-002','Khảo sát hài lòng · Minh Long','Email','08/10 · 09:00','Bản nháp'],['TB-003','Phản ánh tiếng ồn · Green Valley','Điện thoại','08/10 · 08:10','Chờ xử lý']]},
 '14':{label:'Báo cáo & phân tích',icon:'▥',type:'reports',tabs:['Hiệu quả vận hành','Phạm vi tính năng'],action:'In báo cáo'},
 '15':{label:'Tài liệu & tri thức',icon:'▱',type:'docs',tabs:['Thư viện tài liệu','Phạm vi tính năng'],action:'Thêm tài liệu',entity:'tài liệu',cols:['Tên tài liệu','Loại / Phiên bản','Người cập nhật','Trạng thái'],fields:['Tên tài liệu','Loại / Phiên bản','Người cập nhật'],rows:[['TL-001','Checklist bảo trì Mitsubishi','PDF · v2.1','Lê Minh Tuấn','Đã duyệt'],['TL-002','Quy trình cứu hộ thang máy','PDF · v3.0','Nguyễn Hoàng','Đã duyệt'],['TL-003','Biên bản nghiệm thu dịch vụ','DOCX · v1.2','Nguyễn An','Bản nháp']]},
 '16':{label:'Cấu hình & phân quyền',icon:'⚙',type:'settings',tabs:['Cấu hình chung','Phân quyền','Phạm vi tính năng'],action:'Lưu cấu hình'}
};
let saved = {}; let storageAvailable = true;
try { saved = JSON.parse(localStorage.getItem('evl-prototype-v1') || '{}') || {}; } catch { storageAvailable = false; }
const state = {records:{},settings:{company:'Thang Máy Vàng',region:'Hồ Chí Minh',sla:'30',remind:true,zalo:false,...saved.settings},notes:saved.notes||{},checklist:saved.checklist||[false,false,false,false],checkin:saved.checkin||'',checkout:saved.checkout||'',permissions:saved.permissions||{}};
for(const [id,c] of Object.entries(config)) state.records[id] = Array.isArray(saved.records?.[id]) ? saved.records[id] : structuredClone(c.rows||[]);
let current = '01', tab = 0, query = '', status = '', month = 9, year = 2026;
const badge = s => `<span class="badge ${/quá hạn|Hết hạn|Khẩn|tối thiểu/.test(s)?'red':/Hoàn thành|hiệu lực|hoạt động|Đã duyệt|Sẵn sàng|Đã thanh toán|khắc phục|Đủ tồn/.test(s)?'green':/Chờ|Chưa|Sắp|nháp|Tiếp nhận/.test(s)?'amber':'blue'}">${escapeHTML(s)}</span>`;
function persist(){try{localStorage.setItem('evl-prototype-v1',JSON.stringify(state));return true;}catch{storageAvailable=false;return false;}}
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4200);}
function savedToast(message){toast(persist()?message:message+' · Không thể lưu lâu dài trên trình duyệt này.');}
const moduleById = id => modules.find(m=>m.id===id);
function nav(){let out='';const groups={'01':'Không gian điều hành','02':'Khách hàng & kinh doanh','06':'Vận hành kỹ thuật','11':'Tài chính & dịch vụ','14':'Quản trị hệ thống'};for(const [id,c] of Object.entries(config).sort()){if(groups[id])out+=`<div class="nav-group">${groups[id]}</div>`;out+=`<a href="#${id}" class="${id===current?'active':''}" ${id===current?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${c.icon}</span>${c.label}<span class="number">${id}</span></a>`;}$('#navigation').innerHTML=out;}
function metric(label,value,foot,icon='↗'){return `<div class="metric"><span class="metric-label">${label}</span><span class="metric-icon">${icon}</span><div class="metric-value">${value}</div><small>${foot}</small></div>`;}
function chart(){return `<div class="chart" role="img" aria-label="Biểu đồ dữ liệu mẫu: số công việc hoàn thành tăng từ tháng 5 đến tháng 10">${[[42,33],[61,50],[54,47],[75,65],[68,61],[94,84]].map((v,i)=>`<div class="bar-group"><div class="bar" style="height:${v[0]}%"></div><div class="bar secondary" style="height:${v[1]}%"></div><small>Tháng ${i+5}</small></div>`).join('')}</div><div class="chart-summary"><span>Hiệu suất hoàn thành so với tháng trước</span><strong>↗ +12,8%</strong></div>`;}
function dashboard(){return `<section class="metrics">${metric('Thang máy đang quản lý','248','<span class="positive">↗ 12 thiết bị</span> so với tháng trước','▥')}${metric('Công việc hôm nay','24','<span class="positive">18 hoàn thành</span> · 6 đang thực hiện','☷')}${metric('Hợp đồng có hiệu lực','186','<span class="negative">8 hợp đồng</span> sắp hết hạn','▤')}${metric('Tỷ lệ bảo trì đúng hạn','96,8%','<span class="positive">↗ 2,4%</span> so với tháng trước','◷')}</section><div class="grid"><section class="panel"><div class="panel-head"><div><h2>Hiệu quả vận hành</h2><small>Khối lượng công việc trong 6 tháng gần nhất</small></div><div class="legend"><span><i class="dot"></i>Kế hoạch</span><span><i class="dot green"></i>Hoàn thành</span></div></div><div class="panel-body">${chart()}</div></section><section class="panel"><div class="panel-head"><h2>Cần bạn chú ý</h2><span class="badge amber">03 mục</span></div><div class="panel-body"><a class="notice" href="#07"><span class="notice-icon red">ϟ</span><div><strong>01 sự cố cần xử lý khẩn cấp</strong><p>Sun Avenue · Thang A2 dừng tầng<br>SLA phản hồi còn 18 phút (mẫu)</p></div></a><a class="notice" href="#05"><span class="notice-icon">▤</span><div><strong>08 hợp đồng sắp hết hạn</strong><p>Lên kế hoạch gia hạn trong 30 ngày tới</p></div></a><a class="notice" href="#08"><span class="notice-icon">☷</span><div><strong>03 công việc chưa phân công</strong><p>Cần điều phối kỹ thuật viên trong hôm nay</p></div></a></div></section></div><div class="grid"><section class="panel"><div class="panel-head"><div><h2>Lịch công việc hôm nay</h2><small>Thứ Năm, ngày 08 tháng 10 năm 2026</small></div><a class="link" href="#08">Xem tất cả ↗</a></div>${table('08',true)}</section><section class="panel"><div class="panel-head"><h2>Trạng thái công việc</h2><span class="subtext">Tháng 10</span></div><div class="panel-body"><div class="donut"><div class="donut-center"><strong>156</strong><small>Tổng công việc mẫu</small></div></div><div class="status-line"><span><i class="dot green"></i>Đã hoàn thành</span><strong>112</strong></div><div class="status-line"><span><i class="dot"></i>Đang thực hiện</span><strong>27</strong></div><div class="status-line"><span>○ Chưa phân công</span><strong>17</strong></div></div></section></div>`;}
function filtered(id){return state.records[id].filter(r=>(!query||r.join(' ').toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')))&&(!status||r[4]===status));}
function table(id,compact=false){const c=config[id], rows=compact?state.records[id].slice(0,4):filtered(id);return `<div class="table-wrap"><table><thead><tr>${c.cols.filter((_,i)=>!compact||i!==1).map(x=>`<th>${x}</th>`).join('')}<th aria-label="Thao tác"></th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="row-open" data-record="${escapeHTML(r[0])}" data-module="${id}">${escapeHTML(r[1])}</button><small>${escapeHTML(r[0])}</small></td>${compact?'':`<td>${escapeHTML(r[2])}</td>`}<td>${escapeHTML(r[3])}</td><td>${badge(r[4])}</td><td><button class="row-open" data-record="${escapeHTML(r[0])}" data-module="${id}" aria-label="Xem ${escapeHTML(r[1])}">↗</button></td></tr>`).join('')||`<tr><td colspan="5" class="empty">Không có kết quả phù hợp. Hãy thay đổi từ khóa hoặc bộ lọc.</td></tr>`}</tbody></table></div>${compact?'':`<div class="table-foot"><span>Hiển thị ${rows.length} / ${state.records[id].length} bản ghi mẫu</span><span>Trang 1 / 1</span></div>`}`;}
function toolbar(){const c=config[current];return `<div class="toolbar"><div class="filters"><input type="search" id="record-search" placeholder="Tìm tên, mã hoặc người phụ trách…" aria-label="Tìm bản ghi" value="${escapeHTML(query)}"><select id="status-filter" aria-label="Lọc trạng thái"><option value="">Tất cả trạng thái</option>${[...new Set(state.records[current].map(r=>r[4]))].map(s=>`<option ${s===status?'selected':''}>${escapeHTML(s)}</option>`).join('')}</select></div><button data-action="export">↓ Xuất CSV</button></div>`;}
function recordsView(){return `<section class="panel">${toolbar()}<div id="record-results">${table(current)}</div></section>`;}
function board(){const c=config[current];return `${toolbar()}<div id="record-results">${boardContent()}</div>`;}
function boardContent(){return `<div class="board">${config[current].states.map(s=>{const rows=filtered(current).filter(r=>r[4]===s);return `<section class="lane"><h3>${s}<span class="badge">${rows.length}</span></h3>${rows.map(r=>`<button class="kanban-card" data-record="${escapeHTML(r[0])}" data-module="${current}"><span class="feature-id">${escapeHTML(r[0])}</span><strong>${escapeHTML(r[1])}</strong><span class="subtext">${escapeHTML(r[2])}</span><div class="card-bottom"><span>${escapeHTML(r[3])}</span><span>Chi tiết ↗</span></div></button>`).join('')||'<div class="subtext">Chưa có bản ghi</div>'}</section>`;}).join('')}</div>`;}
function calendar(){const days=new Date(year,month+1,0).getDate(), offset=(new Date(year,month,1).getDay()+6)%7;return `<section class="panel"><div class="toolbar"><div class="actions"><button data-month="-1" aria-label="Tháng trước">←</button><strong class="month-title">Tháng ${month+1}, ${year}</strong><button data-month="1" aria-label="Tháng sau">→</button><button data-action="today">Tháng mẫu hiện tại</button></div><span class="subtext"><i class="dot green"></i>Đã lên lịch &nbsp; <i class="dot"></i>Đề xuất dời lịch</span></div><div class="table-wrap"><div class="calendar">${['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'].map(d=>`<div class="weekday">${d}</div>`).join('')}${Array.from({length:Math.ceil((days+offset)/7)*7},(_,i)=>{const d=i-offset+1;const date=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;return `<div class="day ${d===8&&month===9&&year===2026?'today':''}">${d>0&&d<=days?`<span>${d}</span>${state.records['06'].filter(r=>r[2]===date).map(r=>`<button class="event ${r[4].includes('Chờ')?'yellow':''}" data-record="${escapeHTML(r[0])}" data-module="06">${escapeHTML(r[1])}<small>${escapeHTML(r[3])}</small></button>`).join('')}`:''}</div>`;}).join('')}</div></div></section>`;}
function field(){return `<div class="field-layout"><div class="panel"><div class="panel-head"><h2>Luồng làm việc tại hiện trường</h2>${badge('Mô phỏng mobile')}</div><div class="panel-body"><p class="subtext">Kỹ thuật viên tiếp nhận công việc, check-in, kiểm tra thiết bị và hoàn tất biên bản tại công trình.</p><div class="timeline"><p><strong>01 · Tiếp nhận công việc</strong><small>Thông tin khách hàng, thiết bị và lịch hẹn</small></p><p><strong>02 · Check-in tại công trình</strong><small>Thời gian được lưu thử; vị trí GPS chưa được thu thập</small></p><p><strong>03 · Thực hiện checklist</strong><small>Kiểm tra an toàn, vận hành và ghi chú phát sinh</small></p><p><strong>04 · Biên bản & nghiệm thu</strong><small>Xem bố cục biên bản từ danh mục tính năng 09.14–09.15</small></p></div><a class="primary" style="display:inline-block;padding:10px 16px;border-radius:8px" href="#08">Mở bảng điều phối ↗</a></div></div><div class="mobile-preview"><p class="eyebrow">THANG MÁY VÀNG · FIELD SERVICE</p><h2>Chào Tuấn 👋</h2><p class="subtext">Thứ Năm, 08/10 · 3 công việc hôm nay</p><div class="panel"><div class="panel-body">${badge(state.checkout?'Hoàn thành':state.checkin?'Đang thực hiện':'Đã phân công')}<h3 style="margin-top:14px">Bảo trì định kỳ thang A1</h3><p class="subtext">The Sun Avenue · TM-001<br>28 Mai Chí Thọ, TP. Thủ Đức<br>Hẹn 08:30 – 10:00</p><button class="primary" style="width:100%" data-action="checkin" ${state.checkin?'disabled':''}>${state.checkin?'Đã check-in · '+escapeHTML(state.checkin):'◎ Check-in mô phỏng'}</button></div></div><div class="panel"><div class="panel-body"><h3>Checklist bảo trì</h3><div class="checklist">${['Kiểm tra cửa tầng và khóa an toàn','Kiểm tra cáp tải và đối trọng','Kiểm tra hệ thống cứu hộ tự động','Chạy thử và vệ sinh cabin'].map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${state.checklist[i]?'checked':''} ${!state.checkin||state.checkout?'disabled':''}><span>${x}</span></label>`).join('')}</div><p class="subtext" id="check-progress" style="margin-top:12px">${state.checklist.filter(Boolean).length}/4 hạng mục hoàn thành</p><button data-action="checkout" class="primary" style="width:100%" ${!state.checkin||!state.checklist.every(Boolean)||state.checkout?'disabled':''}>${state.checkout?'Đã hoàn tất · '+escapeHTML(state.checkout):'Hoàn tất & check-out thử'}</button></div></div></div></div>`;}
function reports(){return `<div class="toolbar"><div class="filters"><label class="subtext">Kỳ báo cáo <select id="report-period"><option>Tháng 10/2026</option><option>Tháng 09/2026</option></select></label><span class="subtext">Toàn chi nhánh · Dữ liệu minh họa</span></div><button data-action="print">In / Lưu PDF</button></div><div id="report-content">${reportContent(false)}</div>`;}
function reportContent(previous){return `<div class="metrics">${metric('Doanh thu dịch vụ',previous?'842 tr':'950 tr','Số liệu minh họa','₫')}${metric('Bảo trì đúng hạn',previous?'94,4%':'96,8%','Theo lịch đã cam kết','◷')}${metric('SLA phản hồi',previous?'93,2%':'98,2%','Tỷ lệ đạt mục tiêu','ϟ')}${metric('Hài lòng khách hàng',previous?'4,6/5':'4,8/5','Từ 86 phản hồi mẫu','☆')}</div><div class="grid"><section class="panel"><div class="panel-head"><h2>Khối lượng công việc · 6 tháng gần nhất</h2></div><div class="panel-body">${chart()}</div></section><section class="panel"><div class="panel-head"><h2>Hiệu suất kỹ thuật viên · ${previous?'09':'10'}/2026</h2></div><div class="panel-body report-bars">${['Lê Minh Tuấn','Trần Quốc Huy','Nguyễn Hoàng','Võ Thanh Bình'].map((n,i)=>`<div>${n}<strong>${(previous?91:98)-i*5}%</strong><div class="progress"><span style="width:${(previous?91:98)-i*5}%"></span></div></div>`).join('')}</div></section></div>`;}
function docs(){return `<div class="folder-grid" style="margin-bottom:22px">${['Quy trình & hướng dẫn','Hồ sơ kỹ thuật','Biểu mẫu & checklist'].map((x,i)=>`<button class="folder" data-folder="${i}"><span class="folder-icon">▰</span><strong>${x}</strong><small>Mở tài liệu mẫu ↗</small></button>`).join('')}</div>${recordsView()}`;}
function settings(){return `<div class="settings-grid"><section class="panel"><div class="panel-head"><h2>Thông tin tổ chức</h2>${badge('Cấu hình mẫu')}</div><div class="panel-body"><div class="form-grid"><label class="wide">Tên công ty<input id="setting-company" value="${escapeHTML(state.settings.company)}" required></label><label class="wide">Khu vực mặc định<input id="setting-region" value="${escapeHTML(state.settings.region)}" required></label><label class="wide">SLA phản hồi sự cố (phút)<input id="setting-sla" type="number" min="1" max="1440" value="${escapeHTML(state.settings.sla)}"></label></div></div></section><section class="panel"><div class="panel-head"><h2>Thông báo & tự động hóa</h2></div><div class="panel-body"><label class="setting-row"><span>Nhắc lịch bảo trì<small>Nhắc trước ngày hẹn theo hợp đồng</small></span><input id="setting-remind" type="checkbox" ${state.settings.remind?'checked':''}></label><label class="setting-row"><span>Kênh Zalo OA<small>Chỉ lưu tùy chọn mẫu, chưa kết nối dịch vụ</small></span><input id="setting-zalo" type="checkbox" ${state.settings.zalo?'checked':''}></label><div class="setting-row"><span>Phiên bản prototype<small>Dữ liệu lưu cục bộ trên trình duyệt</small></span>${badge('v1.0')}</div><button data-action="reset" class="danger" style="margin-top:20px">Khôi phục dữ liệu mẫu</button></div></section></div>`;}
function permissions(){return `<section class="panel"><div class="panel-head"><div><h2>Ma trận quyền theo vai trò</h2><small>Bố cục minh họa; không thực thi bảo mật trong prototype</small></div><button data-action="save-permissions" class="primary">Lưu ma trận mẫu</button></div><div class="table-wrap"><table class="permission-table"><thead><tr><th>Phân hệ</th>${['Quản trị','Kinh doanh','Điều phối','Kỹ thuật'].map(r=>`<th>${r}</th>`).join('')}</tr></thead><tbody>${modules.map(m=>`<tr><td>${m.name}</td>${[0,1,2,3].map(r=>{const key=m.id+'-'+r;return `<td><input type="checkbox" data-permission="${key}" aria-label="Quyền ${['Quản trị','Kinh doanh','Điều phối','Kỹ thuật'][r]} với ${m.name}" ${(state.permissions[key]??(r===0||r===2||r===1&&+m.id<6||r===3&&+m.id>=6&&+m.id<=10))?'checked':''}></td>`;}).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
function features(){const fs=moduleById(current).features;return `<p class="cover-note">${fs.length} tính năng từ tài liệu gốc. Chọn một mục để duyệt bố cục chi tiết và các trường dữ liệu đề xuất.</p><div class="toolbar" style="padding:0 0 20px"><input id="feature-search" type="search" aria-label="Tìm tính năng" placeholder="Tìm theo tên hoặc mã tính năng…"><span class="subtext">${moduleById(current).name}</span></div><div class="feature-grid" id="feature-results">${featureCards(fs)}</div>`;}
function featureCards(fs){return fs.map(f=>`<button class="feature-card" data-feature="${f.id}"><span class="feature-id">${f.id} <span class="badge">Giai đoạn ${window.featurePhases[f.id]||2}</span></span><span>${escapeHTML(f.name)}</span><small>Xem layout chi tiết ↗</small></button>`).join('')||'<p class="empty">Không tìm thấy tính năng.</p>';}
function render(){const c=config[current];document.title=c.label+' · Thang Máy Vàng';$('#crumb').textContent=c.label;nav();$('#main').innerHTML=`<div class="page-head"><div><p class="eyebrow">${current==='01'?'WORKSPACE / OVERVIEW':'WORKSPACE / MODULE '+current}</p><h1>${current==='01'?'Tổng quan điều hành':c.label}</h1><div class="subtext">${current==='01'?'Chào buổi sáng, An. Cùng theo dõi hoạt động hôm nay.':moduleById(current).features.length+' tính năng · CRM & quản lý dịch vụ thang máy'}</div></div><div class="actions">${current==='01'?'<button data-action="scope">◫ Phạm vi tính năng</button><button data-action="print">↓ Xuất tổng quan</button>':'<button data-action="scope">◫ Phạm vi tính năng</button>'}<button class="primary" data-action="primary">${['14','16'].includes(current)?'':'＋ '}${c.action}</button></div></div>${(current!=='01'||tab!==0)?`<div class="tabs" role="tablist" aria-label="Chế độ xem">${c.tabs.map((t,i)=>`<button role="tab" aria-selected="${tab===i}" class="${tab===i?'active':''}" data-tab="${i}">${t}</button>`).join('')}</div>`:''}${!storageAvailable?'<div class="banner">Trình duyệt không hỗ trợ lưu cục bộ. Thao tác chỉ được giữ trong phiên này.</div>':''}<div id="view">${view()}</div>`;}
function view(){const c=config[current];if(tab===c.tabs.length-1)return features();if(tab===1){if(current==='16')return permissions();return recordsView();}switch(c.type){case'dashboard':return dashboard();case'board':return board();case'calendar':return calendar();case'field':return field();case'reports':return reports();case'docs':return docs();case'settings':return settings();default:return `${current==='07'?'<div class="banner">ϟ Sự cố khẩn cấp đang xử lý: Sun Avenue A2 · SLA mẫu còn 18 phút. Chọn hồ sơ để phân công và cập nhật trạng thái.</div>':''}${recordsView()}`;}}
function openDialog(title,body,foot='',eyebrow='CHI TIẾT NGHIỆP VỤ'){const d=$('#dialog');d.innerHTML=`<div class="dialog-head"><div><p class="eyebrow">${eyebrow}</p><h2 id="dialog-title">${escapeHTML(title)}</h2></div><button data-action="close" aria-label="Đóng hộp thoại">✕</button></div><div class="dialog-body">${body}</div>${foot?`<div class="dialog-foot">${foot}</div>`:''}`;if(!d.open)d.showModal();}
function recordDetail(id,key){const r=state.records[id].find(x=>x[0]===key);if(!r)return;const c=config[id];openDialog(r[1],`${badge(r[4])}<div class="detail-grid">${[['Mã hồ sơ',r[0]],[c.cols[1],r[2]],[c.cols[2],r[3]],['Phân hệ',c.label]].map(([k,v])=>`<div class="detail-item"><small>${escapeHTML(k)}</small>${escapeHTML(v)}</div>`).join('')}</div><h3>Liên kết nghiệp vụ</h3><div class="actions"><button data-link="02">Khách hàng</button><button data-link="04">Hồ sơ thang máy</button><button data-link="05">Hợp đồng</button><button data-link="08">Công việc</button></div><h3 style="margin-top:22px">Ghi chú</h3><p class="subtext">${escapeHTML(state.notes[key]||'Hồ sơ mẫu phục vụ duyệt giao diện và luồng thao tác.')}</p><div class="timeline"><p>Hồ sơ được đưa vào dữ liệu prototype<small>08/10/2026 · Quản trị vận hành</small></p></div>`,`<button class="danger" data-delete="${escapeHTML(key)}" data-module="${id}">Xóa bản ghi mẫu</button><button class="primary" data-edit="${escapeHTML(key)}" data-module="${id}">Chỉnh sửa</button>`);}
function editRecord(id,key){const c=config[id],r=state.records[id].find(x=>x[0]===key),states=c.states||[...new Set(state.records[id].map(x=>x[4]).concat(['Bản nháp','Đang hoạt động']))];openDialog(r?'Chỉnh sửa '+c.entity:c.action,`<form id="record-form" data-module="${id}" data-key="${escapeHTML(key||'')}"><div class="form-grid">${c.fields.map((f,i)=>`<label class="${i===0?'wide':''}">${escapeHTML(f)} <span class="negative">*</span><input name="f${i}" ${id==='06'&&i===1?'type="date"':'type="text"'} required maxlength="180" value="${escapeHTML(r?.[i+1]||'')}"></label>`).join('')}<label>Trạng thái<select name="status">${states.map(s=>`<option ${s===r?.[4]?'selected':''}>${escapeHTML(s)}</option>`).join('')}</select></label><label class="wide">Ghi chú<textarea name="note" maxlength="1500">${escapeHTML(state.notes[key]||'')}</textarea></label></div><p class="subtext" style="margin-top:18px">Dữ liệu thử được lưu trên trình duyệt. Không gửi đến khách hàng hoặc hệ thống bên ngoài.</p></form>`,`<button data-action="close">Hủy</button><button class="primary" type="submit" form="record-form">Lưu ${c.entity}</button>`,'BIỂU MẪU / '+id);}
function featureDetail(key){const m=moduleById(key.split('.')[0]),f=m.features.find(x=>x.id===key),c=config[m.id];const savedNote=state.notes['feature-'+key]||'';let fields=c.fields||['Tên cấu hình / Báo cáo','Phạm vi áp dụng','Người phụ trách'];if(/lịch|thời hạn|ngày/.test(f.name))fields=['Hồ sơ liên quan','Ngày bắt đầu','Ngày kết thúc / Ngày hẹn'];else if(/quyền|vai trò|truy cập/.test(f.name))fields=['Tài khoản / Vai trò','Phân hệ áp dụng','Phạm vi dữ liệu'];else if(/tài liệu|file|ảnh|chứng nhận/.test(f.name))fields=['Tên tài liệu / Bằng chứng','Hồ sơ / Thiết bị liên quan','Phiên bản / Loại tài liệu'];else if(/SLA|cảnh báo|Cảnh báo/.test(f.name))fields=['Đối tượng theo dõi','Ngưỡng cảnh báo','Người nhận / Cấp xử lý'];else if(/báo cáo|Báo cáo|Thống kê/.test(f.name))fields=['Kỳ báo cáo','Khu vực / Khách hàng','Nhân sự phụ trách'];openDialog(f.name,`<div class="banner">Bố cục đề xuất cho ${key} · Giai đoạn ${window.featurePhases[key]||2}. Chưa triển khai xử lý nghiệp vụ thực tế.</div><h3>Thông tin & bộ lọc</h3><div class="form-grid">${fields.map((x,i)=>`<label class="${i===0?'wide':''}">${escapeHTML(x)}<input placeholder="${escapeHTML(x)}" aria-label="${escapeHTML(x)}"></label>`).join('')}<label>Trạng thái<select><option>Bản nháp</option><option>Chờ duyệt</option><option>Hoàn tất</option></select></label></div><h3 style="margin-top:24px">Vùng nội dung nghiệp vụ</h3><div class="detail-grid"><div class="detail-item"><small>Liên kết hồ sơ</small>Khách hàng → Công trình → Thang máy</div><div class="detail-item"><small>Kiểm soát thao tác</small>Thông tin cập nhật · Lịch sử · Người phụ trách</div></div><label class="subtext" for="feature-note">Ghi chú duyệt layout (được lưu)</label><textarea id="feature-note" style="width:100%;margin-top:6px" placeholder="Ghi nhận yêu cầu bổ sung cho màn hình này…">${escapeHTML(savedNote)}</textarea>`,`<button data-action="close">Đóng</button><button class="primary" data-save-feature="${key}">Lưu ghi chú layout</button>`,m.name+' / '+key);}
function exportCSV(){const rows=filtered(current),c=config[current],csv='\ufeff'+[['Mã',...c.cols],...rows].map(r=>r.map(v=>{let s=String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TMV-'+current+'-du-lieu-mau.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Đã xuất '+rows.length+' bản ghi mẫu.');}
function saveSettings(){const inputs=['company','region','sla'];if(inputs.some(k=>!$('#setting-'+k)?.reportValidity()))return;inputs.forEach(k=>state.settings[k]=$('#setting-'+k).value.trim());['remind','zalo'].forEach(k=>state.settings[k]=$('#setting-'+k).checked);savedToast('Đã lưu cấu hình mẫu.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab!==undefined){tab=Number(b.dataset.tab);query='';status='';render();return;}
 if(b.dataset.record){recordDetail(b.dataset.module,b.dataset.record);return;}
 if(b.dataset.edit){editRecord(b.dataset.module,b.dataset.edit);return;}
 if(b.dataset.feature){featureDetail(b.dataset.feature);return;}
 if(b.dataset.saveFeature){state.notes['feature-'+b.dataset.saveFeature]=$('#feature-note').value;savedToast('Đã lưu ghi chú duyệt layout.');$('#dialog').close();return;}
 if(b.dataset.link){$('#dialog').close();location.hash=b.dataset.link;return;}
 if(b.dataset.delete){const id=b.dataset.module,key=b.dataset.delete;openDialog('Xóa bản ghi mẫu?',`<p>Bản ghi ${escapeHTML(key)} sẽ bị xóa khỏi dữ liệu thử trên trình duyệt.</p>`,`<button data-action="close">Hủy</button><button class="danger" data-confirm-delete="${escapeHTML(key)}" data-module="${id}">Xóa bản ghi</button>`);return;}
 if(b.dataset.confirmDelete){state.records[b.dataset.module]=state.records[b.dataset.module].filter(r=>r[0]!==b.dataset.confirmDelete);delete state.notes[b.dataset.confirmDelete];savedToast('Đã xóa bản ghi mẫu.');$('#dialog').close();render();return;}
 if(b.dataset.month){const d=new Date(year,month+Number(b.dataset.month),1);month=d.getMonth();year=d.getFullYear();render();return;}
 if(b.dataset.folder!==undefined){const records=state.records['15'];const idx=[1,0,2][Number(b.dataset.folder)];if(records[idx])recordDetail('15',records[idx][0]);else toast('Thư mục chưa có tài liệu mẫu.');return;}
 switch(b.dataset.action){case'close':$('#dialog').close();break;case'scope':tab=config[current].tabs.length-1;render();break;case'primary':if(current==='01')editRecord('08');else if(current==='14')window.print();else if(current==='16'){if(tab===0)saveSettings();else if(tab===1)savePermissions();else{tab=0;render();}}else editRecord(current);break;case'export':exportCSV();break;case'print':window.print();break;case'today':month=9;year=2026;render();break;case'checkin':state.checkin=new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});savedToast('Đã check-in mô phỏng.');render();break;case'checkout':if(!state.checkin||!state.checklist.every(Boolean))return;state.checkout=new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});savedToast('Đã hoàn thành công việc mô phỏng.');render();break;case'save-permissions':savePermissions();break;case'reset':openDialog('Khôi phục dữ liệu mẫu?',`<p>Các bản ghi, cấu hình và ghi chú layout bạn tạo trong prototype sẽ bị xóa.</p>`,`<button data-action="close">Hủy</button><button class="danger" data-action="confirm-reset">Khôi phục</button>`);break;case'confirm-reset':try{localStorage.removeItem('evl-prototype-v1');location.reload();}catch{toast('Không thể khôi phục dữ liệu trong trình duyệt này.');}break;}
});
function savePermissions(){document.querySelectorAll('[data-permission]').forEach(el=>state.permissions[el.dataset.permission]=el.checked);savedToast('Đã lưu ma trận quyền mẫu.');}
document.addEventListener('submit',e=>{if(e.target.id!=='record-form')return;e.preventDefault();const form=e.target,id=form.dataset.module,data=new FormData(form);if([0,1,2].some(i=>!String(data.get('f'+i)).trim())){toast('Vui lòng điền đầy đủ các trường bắt buộc.');return;}let key=form.dataset.key;const existing=state.records[id].find(r=>r[0]===key);if(!key){const prefix=config[id].rows?.[0]?.[0].split('-')[0]||'HS';key=prefix+'-'+Date.now().toString(36).toUpperCase();}const row=[key,...[0,1,2].map(i=>String(data.get('f'+i)).trim()),String(data.get('status'))];if(existing)state.records[id][state.records[id].indexOf(existing)]=row;else state.records[id].unshift(row);state.notes[key]=String(data.get('note'));savedToast('Đã lưu bản ghi mẫu.');$('#dialog').close();render();});
document.addEventListener('input',e=>{if(e.target.id==='record-search'){query=e.target.value;$('#record-results').innerHTML=config[current].type==='board'&&tab===0?boardContent():table(current);}if(e.target.id==='feature-search'){const q=e.target.value.toLocaleLowerCase('vi');$('#feature-results').innerHTML=featureCards(moduleById(current).features.filter(f=>(f.id+' '+f.name).toLocaleLowerCase('vi').includes(q)));}});
document.addEventListener('change',e=>{if(e.target.id==='status-filter'){status=e.target.value;$('#record-results').innerHTML=config[current].type==='board'&&tab===0?boardContent():table(current);}if(e.target.dataset.check!==undefined){state.checklist[Number(e.target.dataset.check)]=e.target.checked;persist();$('#check-progress').textContent=state.checklist.filter(Boolean).length+'/4 hạng mục hoàn thành';$('[data-action="checkout"]').disabled=!state.checklist.every(Boolean);}if(e.target.id==='report-period')$('#report-content').innerHTML=reportContent(e.target.selectedIndex===1);});
$('#menu').addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');$('#menu').setAttribute('aria-expanded',String(open));});
$('#notifications').addEventListener('click',()=>openDialog('Thông báo vận hành',`<div class="notice"><span class="notice-icon red">ϟ</span><div><strong>Sự cố Sun Avenue A2</strong><p>Cần theo dõi SLA phản hồi và tiến độ xử lý.</p><button data-link="07">Xem sự cố</button></div></div><div class="notice"><span class="notice-icon">▤</span><div><strong>Hợp đồng Green Valley sắp hết hạn</strong><p>Chuẩn bị phương án gia hạn.</p><button data-link="05">Xem hợp đồng</button></div></div>`));
function route(){const requested=location.hash.slice(1);current=config[requested]?requested:'01';tab=0;query='';status='';document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');if($('#dialog').open)$('#dialog').close();render();window.scrollTo(0,0);}
window.addEventListener('hashchange',route);route();
